### ISSUE TITLE
Renamed colonies appear with their old names

### ISSUE THREAD

**Issue by boterham** [benreid24/Stellaru#39]
Renamed colonies are listed by their old names in graphs such as colony size/stability/etc.

**Comment by benreid24** [comment]
There's two name fields in the game save for each planet, guess I picked the wrong one. Thanks for bringing this up!

**Comment by benreid24** [comment]
Checked it out a bit. The two fields in the game save for planet names are `name` and `custom_name`. The former is the name itself and the latter is either a "yes" or "no". The frontend selects the most recent name available when determining the label for a planet on the chart. Was the game saved since changing the planet name?

**Comment by boterham** [comment]
I did save the game afterwards. Restarting both Stellaris and Stellaru did not fix it either.

**Comment by benreid24** [comment]
Did you use the same version of Stellaru when reinstalling?

**Comment by benreid24** [comment]
I cannot reproduce and the issue appears resolved, so I will close this for now. Please reopen if it occurs again
